const { Router } = require('express');
const { Ticket, Graph } = require('../controllers');

const router = Router();
module.exports = router;

router.get('/admin/tickets', Ticket.readMany);
router.get('/admin/tickets/:id', Ticket.readOne);
router.post('/tickets', Ticket.create);
router.put('/admin/tickets/:id/assign', Ticket.assignEmployee);
router.put('/admin/tickets/:id/answer', Ticket.answerTicket);
router.put('/admin/tickets/:id/close', Ticket.closeTicket);
router.delete('/admin/tickets/:id', Ticket.remove);

router.get('/admin/graph/orders-monthly', Graph.ordersMonthly);
router.get('/admin/graph/payment-yearly', Graph.paymentYearly);

router.get('/admin/stats', Ticket.stats);
/* auto-generated by robocode v0.4.3 */
