module.exports = async () => {
  return [
    {
      series: 'SOTU',
      number: 1,
      status: 'pending',
      invoiceData: {
        firstName: 'Ana',
        lastName: 'Georgescu',
        address: 'Strada Casinilor',
        email: 'ana@gerogescsu.com',
        phone: '0722222222',
        locality: 'Bucuresti',
        county: 'Ilfov',
        country: 'Romania',
      },
      orderTicket: {
        name: 'Anica',
        email: 'anonim@anonim.com',
        motivation: 'Sa nu imi fie frica de intuneric',
        dateReceived: '2023-07-10T09:45:23Z',
        status: 'unassigned',
        message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 17,
        quantity: 1,
      },
      processed: false,
    },
    {
      series: 'SOTU',
      number: 2,
      status: 'pending',
      invoiceData: {
        firstName: 'Calin',
        lastName: 'Popescu',
        address: 'Strada Porcilor',
        email: 'calin@popescu.com',
        phone: '0722222222',
        locality: 'Bucuresti',
        county: 'Ilfov',
        country: 'Romania',
      },
      orderTicket: {
        name: 'Calin',
        email: 'anonim@anonim.com',
        motivation: 'Sa nu imi fie frica de intuneric',
        dateReceived: '2023-07-11T09:45:23Z',
        status: 'unassigned',
        message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 17,
        quantity: 1,
      },
      processed: false,
    },
    {
      series: 'SOTU',
      number: 3,
      status: 'pending',
      invoiceData: {
        firstName: 'Gica',
        lastName: 'Becali',
        address: 'Strada Mea',
        email: 'gica@becali.com',
        phone: '0722222222',
        locality: 'Bucuresti',
        county: 'Ilfov',
        country: 'Romania',
      },
      orderTicket: {
        name: 'Gigi',
        email: 'anonim@anonim.com',
        motivation: 'Sa piarda FCSB',
        dateReceived: '2023-07-16T09:45:23Z',
        status: 'unassigned',
        message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 17,
        quantity: 1,
      },
      processed: false,
    },
    {
      series: 'SOTU',
      number: 4,
      status: 'pending',
      invoiceData: {
        firstName: 'Mircea',
        lastName: 'Gandonescu',
        address: 'Strada Revolutiei',
        email: 'mircea@gandonescu.com',
        phone: '0722222222',
        locality: 'Bucuresti',
        county: 'Ilfov',
        country: 'Romania',
      },
      orderTicket: {
        name: 'Mircea',
        email: 'anonim@anonim.com',
        motivation: 'Sa nu imi fie frica de intuneric',
        dateReceived: '2023-07-29T09:45:23Z',
        status: 'unassigned',
        message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 17,
        quantity: 1,
      },
      processed: false,
    },
    {
      series: 'SOTU',
      number: 5,
      status: 'pending',
      invoiceData: {
        firstName: 'Selena',
        lastName: 'Beleascu',
        address: 'Strada Piersicilor',
        email: 'sel@bel.com',
        phone: '0722222222',
        locality: 'Bucuresti',
        county: 'Ilfov',
        country: 'Romania',
      },
      orderTicket: {
        name: 'Sel',
        email: 'anonim@anonim.com',
        motivation: 'Sa nu imi fie frica de intuneric',
        dateReceived: '2023-07-30T09:45:23Z',
        status: 'unassigned',
        message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 17,
        quantity: 1,
      },
      processed: false,
    },
  ];
};
