const { error, applyFiltersIdentities } = require('../../functions');
const { Identity } = require('../../models');

module.exports = async (req, res) => {
  const filters = applyFiltersIdentities(req.query);
  const identities = await Identity.find(filters);

  if (!identities) {
    throw error(404, 'No identities found');
  }

  return res.status(200).json(identities);
};
/* auto-generated by robocode v0.4.3 */
