const create = require('./create');
const readMany = require('./read-many');
const readOne = require('./read-one');
const remove = require('./remove');
const assignEmployee = require('./assign-employee');
const stats = require('./stats');
const answerTicket = require('./answer-ticket');
const closeTicket = require('./close-ticket');
const updateStatus = require('./update-status');

module.exports = {
  answerTicket,
  assignEmployee,
  closeTicket,
  create,
  readMany,
  readOne,
  remove,
  stats,
  updateStatus,
};
/* auto-generated by robocode v0.4.3 */
