const { error } = require('../../functions');
const { Ticket } = require('../../models');

module.exports = async (req, res) => {
  const { id } = req.params;
  if (!id) {
    throw error(400, 'Missing required params');
  }

  const document = await Ticket.findById(id).select('+updatedAt').lean();
  if (!document) {
    throw error(404, 'Ticket was not found');
  }

  return res.status(200).json(document);
};
/* auto-generated by robocode v0.4.3 */
