const { error } = require('../../functions');
const { Ticket } = require('../../models');

module.exports = async (req, res) => {
  const { id } = req.params;
  if (!id) {
    throw error(400, 'Missing required params');
  }

  const document = await Ticket.findById(id).lean();
  if (!document) {
    throw error(404, 'Ticket was not found');
  }

  // this will permanently delete the item
  await Ticket.findByIdAndDelete(id);

  return res.status(200).send({
    message: 'Ticket was created successfully',
  });
};
/* auto-generated by robocode v0.4.3 */
